name: green
description: Green seu App de finanças.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6996
  get: ^4.6.5
  ionicons: ^0.2.1
  intl: ^0.17.0
  iconsax: ^0.0.8
  flutter_slidable: ^2.0.0
  shared_preferences: ^2.0.15
  email_validator: ^2.1.17
  provider: ^6.0.4
  page_transition: ^1.1.7+6
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  google_fonts: ^3.0.1
  animated_bottom_navigation_bar: ^0.2.1
  bottom_navigation_bar: ^1.0.1
  animated_splash_screen: ^1.0.1+2
  lottie: ^2.0.0
  fl_chart:
  font_awesome: ^5.10.1
  localization: ^2.1.0
  flutter_localization: ^0.1.9
  currency_formatter:
  uuid:
  firebase_core:
  firebase_auth:
  currency_text_input_formatter: ^2.1.7
  font_awesome_flutter: ^10.3.0
  liquid_progress_indicator: ^0.4.0
dev_dependencies:
  flutter_test:

    sdk: flutter


flutter:


  uses-material-design: true



  assets:
    - assets/logo.png
    - assets/login2.png
    - assets/pigSleeping.png
    - assets/contas.png
    - assets/avatar.png
    - assets/metas.png
    - assets/pagamentos.png
    - assets/mcdonalds.png
    - assets/gas-station.png
    - assets/combustivel.png
    - assets/comida.png
    - assets/comidas2.png
    - assets/academia.png
    - assets/academia2.png
    - assets/hospital.png
    - assets/mercado.png
    - assets/metas2.png
    - assets/metas3.png
    - assets/petshop.png
    - assets/profile.png
    - assets/transporte.png
    - assets/viagem.png
    - assets/Transfer.png
    - assets/Transportation.png
    - assets/Education.png
    - assets/food.png
    - assets/starbucks.ico
    - assets/star.png
    - assets/bank.png
    - assets/cash.png
    - assets/charity.png
    - assets/eating.png
    - assets/gift.png
    - assets/screenboard.png
    - assets/screenboard2.png
    - assets/screenboard3.png
    - assets/screenboard4.png
    - assets/screenboard5.png
    - assets/screenboard6.png
    - assets/screenboard7.png
    - assets/teste1.png
    - assets/teste2.png
    - assets/arrow.png
    - assets/screen01.png
    - assets/screen02.png
    - assets/GreenSplash.json
    - assets/greenSleep.json
    - assets/combustivel.png
    - assets/auto.png
    - assets/verified.png
    - assets/favorited.png
    - assets/banco.png
    - assets/cartoes-de-credito.png
    - assets/categorias.png
    - assets/conta.png
    - assets/educacao.png
    - assets/farmacia.png
    - assets/gastos.png
    - assets/gastos2.png
    - assets/mais.png
    - assets/manutencao.png
    - assets/pet-shop.png
    - assets/google.png
    - assets/drink.png
    - assets/fast-food.png
    - assets/gas-pump.png
    - assets/gifts.png
    - assets/hamburger.png
    - assets/health.png
    - assets/maintenance.png
    - assets/online-gaming.png
    - assets/other.png
    - assets/parking-car.png
    - assets/cinema.png
    - assets/carro.png
    - assets/bolsa-de-compras.png
    - assets/home.png
    - assets/kids.png
    - assets/drinks.png
    - assets/restaurant.png
    - assets/restaurant.png
    - assets/sub1.png
    - assets/sub2.png
    - assets/sub4.png
    - assets/sub5.png
    - assets/sub6.png
    - assets/sub7.png
    - assets/sub9.png
    - assets/sub10.png
    - assets/sub11.png
    - assets/sub12.png
    - assets/sub13.png
    - assets/sub14.png
    - assets/sub15.png
    - assets/sub16.png
    - assets/sub17.png
    - assets/sub18.png
    - assets/sub19.png
    - assets/sub20.png
    - assets/sub21.png
    - assets/sub22.png
    - assets/sub23.png
    - assets/sub24.png
    - assets/sub25.png
    - assets/sub26.png
    - assets/sub27.png
    - assets/sub28.png
    - assets/sub29.png
    - assets/sub30.png
    - assets/sub31.png
    - assets/sub32.png
    - assets/sub33.png
    - assets/sub34.png
    - lib/i18n/
    - trabalhando.png



  fonts:

    - family: Khang
      fonts:
        - asset: assets/fonts/Khang-Light.ttf
          weight: 300
        - asset: assets/fonts/Khang-Regular.ttf
          weight: 400
        - asset: assets/fonts/Khang-Medium.ttf
          weight: 500
        - asset: assets/fonts/Khang-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Khang-Bold.ttf
          weight: 700
        - asset: assets/fonts/MyFlutterApp.ttf
          weight: 700


