// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMVQ7-xZlLBYEMhM02Yn0T6L8EgEjYg_4',
    appId: '1:555764640181:web:89eac53154e55072cc91fc',
    messagingSenderId: '555764640181',
    projectId: 'green-a3d97',
    authDomain: 'green-a3d97.firebaseapp.com',
    storageBucket: 'green-a3d97.appspot.com',
    measurementId: 'G-YNSVD58TQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzECb_80C9gFz08uqUacAvOOxcUlyqbKw',
    appId: '1:555764640181:android:0f8d33fe4c841f95cc91fc',
    messagingSenderId: '555764640181',
    projectId: 'green-a3d97',
    storageBucket: 'green-a3d97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFetkKuCh-ilJkRJcZ2yDHyWNEhcraWd4',
    appId: '1:555764640181:ios:83cee40a279283b1cc91fc',
    messagingSenderId: '555764640181',
    projectId: 'green-a3d97',
    storageBucket: 'green-a3d97.appspot.com',
    iosClientId: '555764640181-bs6lepl8pmhj7tfv8h0v2coo2ekha0d4.apps.googleusercontent.com',
    iosBundleId: 'com.br.green.app.green',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFetkKuCh-ilJkRJcZ2yDHyWNEhcraWd4',
    appId: '1:555764640181:ios:83cee40a279283b1cc91fc',
    messagingSenderId: '555764640181',
    projectId: 'green-a3d97',
    storageBucket: 'green-a3d97.appspot.com',
    iosClientId: '555764640181-bs6lepl8pmhj7tfv8h0v2coo2ekha0d4.apps.googleusercontent.com',
    iosBundleId: 'com.br.green.app.green',
  );
}
