// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjy6NC_IKsfbdIbCBJvKI5zEdPKEkm1zs',
    appId: '1:788602332941:web:ebb569b7d821e9060e7244',
    messagingSenderId: '788602332941',
    projectId: 'green-finance-6b4ef',
    authDomain: 'green-finance-6b4ef.firebaseapp.com',
    databaseURL: 'https://green-finance-6b4ef-default-rtdb.firebaseio.com',
    storageBucket: 'green-finance-6b4ef.appspot.com',
    measurementId: 'G-R0VYR7FF3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDva7kxJdgWMRq2OxcK7JhOWt2fvd_U3EE',
    appId: '1:788602332941:android:9abe51114aba0d030e7244',
    messagingSenderId: '788602332941',
    projectId: 'green-finance-6b4ef',
    databaseURL: 'https://green-finance-6b4ef-default-rtdb.firebaseio.com',
    storageBucket: 'green-finance-6b4ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-k8b5NVBLPYdBrmKW9PGBtolRZKnisSg',
    appId: '1:788602332941:ios:a2c4c1ac9c4c3ba40e7244',
    messagingSenderId: '788602332941',
    projectId: 'green-finance-6b4ef',
    databaseURL: 'https://green-finance-6b4ef-default-rtdb.firebaseio.com',
    storageBucket: 'green-finance-6b4ef.appspot.com',
    androidClientId: '788602332941-n2kdif0g0fap6tiq8ieqv1cnc65g3hbh.apps.googleusercontent.com',
    iosClientId: '788602332941-mc87n5bci10vs7fp35rgv30eajic0li5.apps.googleusercontent.com',
    iosBundleId: 'com.br.green.app.green',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-k8b5NVBLPYdBrmKW9PGBtolRZKnisSg',
    appId: '1:788602332941:ios:a2c4c1ac9c4c3ba40e7244',
    messagingSenderId: '788602332941',
    projectId: 'green-finance-6b4ef',
    databaseURL: 'https://green-finance-6b4ef-default-rtdb.firebaseio.com',
    storageBucket: 'green-finance-6b4ef.appspot.com',
    androidClientId: '788602332941-n2kdif0g0fap6tiq8ieqv1cnc65g3hbh.apps.googleusercontent.com',
    iosClientId: '788602332941-mc87n5bci10vs7fp35rgv30eajic0li5.apps.googleusercontent.com',
    iosBundleId: 'com.br.green.app.green',
  );
}
