const List categories = [
  {"name": "+ Green", "icon": "assets/metas3.png"},
  {"name": "Combustível", "icon": "assets/combustivel.png"},
  {"name": "Alimentação", "icon": "assets/eating.png"},
  {"name": "Auto", "icon": "assets/auto.png"},
  {"name": "Saúde", "icon": "assets/hospital.png"},
  {"name": "Compras", "icon": "assets/mercado.png"},
  {"name": "Feira", "icon": "assets/comidas2.png"},
  {"name": "Educação", "icon": "assets/Education.png"},
  {"name": "Banco", "icon": "assets/bank.png"},
  {"name": "Cartões", "icon": "assets/Transfer.png"},
  {"name": "Pet Shop", "icon": "assets/petshop.png"},
  {"name": "Academia", "icon": "assets/academia2.png"},
  {"name": "Viagem", "icon": "assets/viagem.png"},
  {"name": "Farmácia", "icon": "assets/famacia.png"},
];
const List<String> categories_ = [
  "+ Green",
  "fuel",
  "feed",
  "auto",
  "health",
  "shopping",
  "trade_fair",
  "education",
  "bank",
  "cards",
  "pet_shop",
  "academy",
  "travel",
  "pharmacy",
];
const List<String> images = [
  "assets/metas3.png",
  "assets/combustivel.png",
  "assets/eating.png",
  "assets/auto.png",
  "assets/hospital.png",
  "assets/mercado.png",
  "assets/comidas2.png",
  "assets/Education.png",
  "assets/bank.png",
  "assets/Transfer.png",
  "assets/petshop.png",
  "assets/academia2.png",
  "assets/viagem.png",
  "assets/famacia.png",
];
